alter table metal_types alter column id drop identity;
alter table metal_types alter column id add generated by default as identity (restart with 1);
update metal_types set id = default;
alter table metal_types alter column id set generated always;